apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopping-list-manager-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shopping-list-manager-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: 30081
  selector:
    {{- include "shopping-list-manager-helm.selectorLabels" . | nindent 4 }}
