server:
    port: 8081
spring:
    application:
        name: '@project.artifactId@'
        version: '@project.version@'
    datasource:
        generate-unique-name: false
        name: shopping-list-manager
        password: sa
    h2:
        console:
            enabled: true
    jackson:
        default-property-inclusion: non_null
        deserialization:
            fail-on-unknown-properties: false
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
        open-in-view: false
        show-sql: true
management:
    endpoint:
      health:
        show-details: ALWAYS
    endpoints:
        web:
            exposure:
                include: '*'
                #include: health,metrics,prometheus
    #otlp:
    #    metrics:
    #        export:
    #            url: http://localhost:4318/v1/metrics
    #            step: 10s
    #    tracing:
    #        endpoint: http://localhost:4318/v1/traces
    tracing:
        sampling:
            probability: 1.0

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace

shoppingListManager:
    cart:
        creation:
            rateLimitPerUser: 5