{
 "title": "Spring Boot 3.x Statistics",
 "description": "Spring Boot Dashboard adapted from https://grafana.com/grafana/dashboards/10280-microservices-spring-boot-2-1/",
 "tags": [ "app" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_info,application)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(jvm_info,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info{application=\"$application\", namespace=\"$Namespace\"},instance)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", namespace=\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\", namespace=\"$Namespace\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\", namespace=\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\", namespace=\"$Namespace\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\", namespace=\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\", namespace=\"$Namespace\"}",
     "legendFormat": "Open Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", namespace=\"$Namespace\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\", namespace=\"$Namespace\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\", namespace=\"$Namespace\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\", namespace=\"$Namespace\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
     "repeat": "memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_nonheap:raw}\", namespace=\"$Namespace\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_nonheap:raw}\", namespace=\"$Namespace\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"${memory_pool_nonheap:raw}\", namespace=\"$Namespace\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\", namespace=\"$Namespace\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\", namespace=\"$Namespace\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\", namespace=\"$Namespace\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\", namespace=\"$Namespace\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Connection Pool HikariCP  Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\", namespace=\"$Namespace\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\", namespace=\"$Namespace\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\", namespace=\"$Namespace\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\", namespace=\"$Namespace\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\", namespace=\"$Namespace\"}"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Creation Time"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Usage Time"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Acquire Time"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*(prometheus|health).*\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"none\", uri!~\".*(prometheus|health).*\", namespace=\"$Namespace\"}[$__rate_interval]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"none\",uri!~\".*(prometheus|health).*\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "INFO logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Spring AI Metrics Dashboard",
 "tags": [
  "ai",
  "spring",
  "metrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AI Metrics Dashboard",
   "type": "stat",
   "description": "Overview of key AI metrics",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Total AI Requests",
   "type": "stat",
   "description": "Total number of AI requests made",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gen_ai_client_operation_seconds_count)",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "gauge",
   "description": "Average response time in milliseconds",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(gen_ai_client_operation_seconds_sum[1m]) / rate(gen_ai_client_operation_seconds_count[1m]) * 1000",
     "legendFormat": "Average Response Time"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "description": "Success rate of AI requests",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(gen_ai_client_operation_seconds_count{error=\"none\"}) / sum(gen_ai_client_operation_seconds_count)) * 100",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "Current error rate of AI requests",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(gen_ai_client_operation_seconds_count{error=\"none\"}) / sum(gen_ai_client_operation_seconds_count))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Token Usage",
   "type": "timeseries",
   "description": "Token usage over time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gen_ai_client_token_usage_total{gen_ai_token_type=\"input\"}) by (gen_ai_token_type)",
     "legendFormat": "Prompt Tokens"
    },
    {
     "expr": "sum(gen_ai_client_token_usage_total{gen_ai_token_type=\"output\"}) by (gen_ai_token_type)",
     "legendFormat": "Completion Tokens"
    }
   ]
  },
  {
   "title": "Response Time Distribution",
   "type": "timeseries",
   "description": "Response time distribution over time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(gen_ai_client_operation_seconds_bucket{error=\"none\"}[5m])) by (le)) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(gen_ai_client_operation_seconds_bucket{error=\"none\"}[5m])) by (le)) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gen_ai_client_operation_seconds_bucket{error=\"none\"}[5m])) by (le)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gen_ai_client_operation_seconds_bucket{error=\"none\"}[5m])) by (le)) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Total Tokens Used",
   "type": "timeseries",
   "description": "Total tokens used over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gen_ai_client_token_usage_total{gen_ai_token_type=\"total\"})",
     "legendFormat": "Total Tokens"
    }
   ]
  },
  {
   "title": "Errors by Model and Operation",
   "type": "timeseries",
   "description": "Errors by LLM model and operation type",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gen_ai_client_operation_seconds_count{error!=\"none\"}) by (gen_ai_request_model, gen_ai_operation_name)",
     "legendFormat": "{{gen_ai_operation_name}} - {{gen_ai_request_model}}"
    }
   ]
  },
  {
   "title": "System Resource Usage",
   "type": "timeseries",
   "description": "System resource usage for the AI application",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "CPU Usage" },
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"} / jvm_memory_max_bytes{area=\"heap\"} * 100",
     "legendFormat": "Heap Memory Usage"
    }
   ]
  }
 ]
}